import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav className="p-5 flex justify-center">
            <Link
              className="p-1 hover:bg-gray-300"
              href="/"
            >
              Home
            </Link>
            <Link
              className="p-1 hover:bg-gray-300"
              href="/launch-detail"
            >
              Launch Detail
            </Link>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
